##########################################################
########## CordisModules AuditViewer Build ###############
##########################################################

##################### Triggers ###########################
trigger:
- master


#################### Build Pool ##########################
pool:
 vmImage: 'windows-latest'
################### Variables ############################
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'master'
  
###################### Build Name ########################
name: $(version.major).$(version.minor).$(version.build).$(BuildID)

##########################################################
####################### Build Steps ######################
##########################################################
steps:

###################### Install NuGet #####################
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '54582f70-b76f-45af-95a3-4715f3d98a8a'

###############Build ####################
- task: VSBuild@1 
  inputs:
    solution: '$(solution)'
    msbuildArgs: 'build'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: 'true'
##########################################################
#############   CordisModules AuditViewer ################
##########################################################
#- template: build/mineRP.CAF.Modules.CordisAuditViewer 
 # parameters:
  # projectFolder: '$(foldermineRP.CAF.Modules.CordisAuditViewer)'
   #restoreSolution: '$(allSolutions)'
   #buildSolution: '$(allSolutions)'
  #  buildPlatform: '$(buildPlatform)'
 #   buildConfiguration: '$(buildConfiguration)'
 #   stagingDirectory: '$(build.artifactStagingDirectory)'
  #  packageSolution: '$(allNuspec)'
 #   updatePackages: [
 #                    "$(foldermineRP.CAF.Modules.CordisAuditViewer)/mineRP.CAF.Modules.CordisAuditViewer/mineRP.CAF.Modules.CordisAuditViewer.sln"
 #                   ]