##########################################################
########## CordisModules AuditViewer Build ###############
##########################################################

##################### Triggers ###########################
trigger:
- master


#################### Build Pool ##########################
pool:

  vmImage: 'windows-latest'
################### Variables ############################
variables:
- group: versioning-group
- group: build-setup-group
- group: repo-folder-group
###################### Build Name ########################
name: $(version.major).$(version.minor).$(version.build).$(BuildID)

##########################################################
####################### Build Steps ######################
##########################################################
steps:

###################### Install NuGet #####################
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'